### PR TITLE
Fix excluding scripts when showing descriptions or scripts contents

### LINKED ISSUE #41: Description + Exclude
`ntl -d -e start`
Didn't exlude start script from menu

### PR DESCRIPTION
**Pull request by mischah**
Fixes #41 

The `--exclude` option now works with `--info` and `--descriptions` 🙈 

image

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -104,7 +104,7 @@ const input = (argv.info || argv.descriptions
 ).filter(
 	// filter excluded scripts
 	i =>
-		!argv.exclude || !argv.exclude.some(e => new RegExp(e + (e.includes('*') ? '' : '$'), 'i').test(i))
+		!argv.exclude || !argv.exclude.some(e => new RegExp(e + (e.includes('*') ? '' : '$'), 'i').test(argv.info || argv.descriptions ? i.value : i))
```
Comment (ruyadorno) [inline cli.js]: it'd be nice to make a refactor later to break this loooooooong line into smaller blocks for readability 😊

Comment (mischah) [reply cli.js]: Jop. Absolutely 🙈
